### ISSUE TITLE
Problem understanding tightly coupled examples

### ISSUE THREAD

**Issue by kumar88kanishk** [node-webrtc/node-webrtc-examples#10]
Hi author,

I would like to thank you for the efforts, but they are too complicated to understand.
The purpose of any reusable package/library is not spend much time and effort, but looking these tightly coupled examples, where directory names, urls, function are all so unreadable. Also there are no comments in the examples. Since you have made everything dynamic, comments would have made things easier. Looking at the chunks of files, confuses me. This repo doesnt even qualify to be examples. This just an implementation.
Very sad to see this.
I was looking for a simple implementation for it.

**Comment by markandrus** [comment]
> This repo doesnt even qualify to be examples. This just an implementation.

I think you are using a different definition of “examples”. The README.md states the goal of the project, which is to show a few examples of how to use node-webrtc, specifically the non-standard APIs for interacting with audio/video from Node. The goal of this project is not to explain the standard WebRTC APIs.

> I was looking for a simple implementation for it.

If you are looking for something else, please explicitly state so and maybe I or another contributor can try to provide you a solution.

**Comment by kumar88kanishk** [comment]
I am looking to implement faceapi with wrtc, 
https://github.com/justadudewhohacks/face-api.js/issues/472
this is the server side implementation, when i simply paste this in any of your examples/<any>/server.js. It works perfectly
My requirement is to untangle the whole implementation of wrtc into a separate project with just 3 files in it (client, server, index) with this faceapi piece of code in server.s

If you can paste all of this in just 3 files. I would be really thankful

**Comment by kumar88kanishk** [comment]
> > This repo doesnt even qualify to be examples. This just an implementation.
> 
> I think you are using a different definition of “examples”. The README.md states the goal of the project, which is to show a few examples of how to use node-webrtc, specifically the non-standard APIs for interacting with audio/video from Node. The goal of this project is not to explain the standard WebRTC APIs.
> 
> > I was looking for a simple implementation for it.
> 
> If you are looking for something else, please explicitly state so and maybe I or another contributor can try to provide you a solution.


No i don't think that i have a different definition of an example.
What i want to say is we look for a easier implementation, We the developers can make start and stop buttons via js,  no one needs complicated, uncommented code as an example. 
https://www.youtube.com/watch?v=rI8tNMsozo0
This link is a rich hickey talk (creator of clojure) , hope this clears the clutter while writing programs

**Comment by modeswitch** [comment]
Hi Kumar,

Your issue is unlikely to get resolved here. It sounds like you have a very specific use case and you should either 1) fork this repository so that you can customize it to your needs, or 2) make a pull requests that satisfies your requirements and is technically and philosophically compatible with this project.
