### ISSUE TITLE
Question: Compositing from multiple clients and reusing stream

### ISSUE THREAD

**Issue by ldenoue** [node-webrtc/node-webrtc-examples#16]
The canvas compositing example is great, thank you.

I’d like to extend it to support compositing several client streams into one frame (think tiling participants videos into one frame)

I think it’s easy to draw a client frame into a part of the canvas.

However, would it be possible to reuse this result to send all peers?

**Comment by markandrus** [comment]
Take a look at the broadcasting example that was recently added. With some extra work, it should be possible to build what you describe.
