### ISSUE TITLE
websocket udp

### ISSUE THREAD

**Issue by vinnitu** [node-webrtc/node-webrtc-examples#19]
Hello!

I need udp channel data from node server to browser client (now it is tcp with websockets).
Is it possibe do with your project? If so can you help me to understand what i need to do?

Thank you!

**Comment by yandeu** [comment]
I wrote a library which does just that (on top of node-webrtc). It was designed for real time multiplayer games, but you can use it for anything you want. Check it out at [geckos.io](https://github.com/geckosio/geckos.io#readme).

**Comment by vinnitu** [comment]
perfectly! do you have multicast?

**Comment by yandeu** [comment]
What do you mean by multicast? Sending some messages only to clients in a certain group? Yes, this is possible by adding the channel to a group with `channel.join("some-group-name")`.

See the [cheatsheet](https://github.com/geckosio/geckos.io/blob/master/cheatsheet.md) with all available methods.

**Comment by vinnitu** [comment]
maybe I am was not correct really i need https://en.wikipedia.org/wiki/Broadcasting_(networking)

**Comment by yandeu** [comment]
From the cheatsheet:
```js
// emits a message to all channels
io.emit('chat message', 'Hello everyone!')
```
It will send a message from the server to all connected clients.

**Comment by yandeu** [comment]
@vinnitu Is this what you where looking for?
