### ISSUE TITLE
Is the record-audio-video-stream example works ??

### ISSUE THREAD

**Issue by Malsoine** [node-webrtc/node-webrtc-examples#25]
Hey guys,

When the message 'start recording' appears, I have the impression that the server crashes, I can't stop the record, or go to another example. Is this normal? Even when I wait a long time to do the conversion, nothing I can't stop the record. 

Someone can help me ? :D

**Comment by codersneha3012** [comment]
Yes, it is working on my system. Did you check the browser console for any error?

**Comment by Malsoine** [comment]
Well, i've tested on a test server, and it works, i'm working on a VM, that probably why i'm having this issue, thanks !
