### ISSUE TITLE
How to record 30 seconds videos with record-audio-video-stream?

### ISSUE THREAD

**Issue by codersneha3012** [node-webrtc/node-webrtc-examples#26]
Hey,

I want it to record videos of 30 seconds each. I have tried duration also but the program stops then,
Can you suggest how can I achieve this?

Currently, it records 1st video - 4 secs, 2nd video - 2 secs, and then 3 rd video continues till I stop.

Please do reply.

**Comment by Malsoine** [comment]
@codersneha3012  I've saw an option in ffmpeg doc named segment you could maybe do what you want with (?) 😄

**Comment by markandrus** [comment]
Sorry, I think this is beyond the scope of this project.
