### ISSUE TITLE
Single simplified example?

### ISSUE THREAD

**Issue by sandipndev** [node-webrtc/node-webrtc-examples#27]
This is quite an elaborate repository. Is there a simplified repo containing maybe a single example without the express app bit.

**Comment by markandrus** [comment]
I left a reply with more context on another thread [here](https://github.com/node-webrtc/node-webrtc-examples/issues/35#issuecomment-700225639). Anyone who would like to discuss, please see my comment and chime in there.

Thanks,
Mark
