### ISSUE TITLE
TypeError: RTCPeerConnection is not a constructor

### ISSUE THREAD

**Issue by helloitsm3** [node-webrtc/node-webrtc-examples#34]
I'm having this error when trying to start any one of the examples that's provided.

![image](https://user-images.githubusercontent.com/13825491/91268876-aa8b4f80-e7a8-11ea-8cc5-472adc740861.png)

**Comment by markandrus** [comment]
Please check if you have any browser plugins that disable WebRTC. Some plugins disable WebRTC for privacy reasons. You may also share your browser version&hellip;

**Comment by helloitsm3** [comment]
> Please check if you have any browser plugins that disable WebRTC. Some plugins disable WebRTC for privacy reasons. You may also share your browser version&hellip;

I disabled it and I'm using the latest version of Firefox

**Comment by markandrus** [comment]
If you mean you disabled WebRTC, it won't work. Otherwise, what do you mean disabled "it"? Separately from this project, you might just try running the following in your browser's console to ensure you can use the WebRTC APIs.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/359154/91654848-9c8d4580-eaac-11ea-9e31-a9705cadc59d.png">

**Comment by helloitsm3** [comment]
> If you mean you disabled WebRTC, it won't work. Otherwise, what do you mean disabled "it"? Separately from this project, you might just try running the following in your browser's console to ensure you can use the WebRTC APIs.
> 
> 
> 
> <img width="327" alt="image" src="https://user-images.githubusercontent.com/359154/91654848-9c8d4580-eaac-11ea-9e31-a9705cadc59d.png">
> 
> 

Sorry I meant I disabled all the extensions that is blocking WebRTC.

**Comment by markandrus** [comment]
Did you try running the test I mentioned? Type `new RTCPeerConnection` into your browser console to see if it works?

Anyway, I cannot triage without more information. Please re-open if you have anything new to share.

**Comment by helloitsm3** [comment]
> Did you try running the test I mentioned? Type `new RTCPeerConnection` into your browser console to see if it works?
> 
> 
> 
> Anyway, I cannot triage without more information. Please re-open if you have anything new to share.

Hi, I've tried it and it works.Thank you 👍
