### ISSUE TITLE
Transmitting video via webrtc point to point using the commandline

### ISSUE THREAD

**Issue by marlocarlo** [node-webrtc/node-webrtc-examples#6]
Hello,
Is it possible for me to use node webrtc to redirect video coming in from standard input to another client?

Would any of these examples help me in accomplishing this?
Thanks,
Marlo

**Comment by markandrus** [comment]
Yes, take a look at the RTCVideoSource API. You just need to read the bytes from stdin, in the appropriate format, and pipe them to the RTCVideoSource.
